name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes all
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: '.'
        destination_repo: 'Jokerweek/database-code'
        destination_folder: '.'
        destination_branch: 'main'
        user_email: 'philippe.soubrier@gmail.com'
        user_name: 'flol3622'
        commit_msg: '[GHA] Update deploy.'
